# Jekyll Configuration
theme: linkhub-jekyll-theme

# Site Configuration
name: Leesa Moore's Digital Portfolio
tagline: One hub, all the links you need
description: Explore my work, connect with me, and discover more.

# Favicon Configuration
favicon:
  path: assets/images/favicons/favicon-32x32.png
  type: png

# Website Logo Configuration
image:
  path: assets/images/TopNotch.png
  type: png
  height: 500
  width: 500
  alt: Top-Notch-Solutions

locale: en_GB
ga4: G-9LJKQM0ZYN

# Verified Badge Configuration
badge:
  enable: true
  icon: ri:verified-badge-fill
  color: '#dfb221'

# Social Links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/leesa-moore/
    path: assets/images/logos--linkedin.png
  - name: Twitter (X)
    url: https://x.com/leeeeesamo
    path: assets/images/devicon--twitter.png

# Resumes Section
resumes:
  - name: Customer Service Manager Resume
    url: assets/resumes/Leesa%20Moore_2025%20Resume_Customer%20Service%20Manager.pdf
    path: assets/images/vscode-icons--file-type-pdf2.png
    tag: Download PDF
  - name: IT Manager Resume
    url: assets/resumes/Leesa%20Moore_2025%20Resume_IT%20Manager.pdf
    path: assets/images/vscode-icons--file-type-pdf2.png
    tag: Download PDF


- name: Accomplishments
  items:
    - url: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll%202022.png
      image: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll%202022.png
      label: "Honor Roll"
    - url: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll%20July%202022.png
      image: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll%20July%202022.png
      label: "Honor Roll"
    - url: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll.png
      image: /assets/accomplishments/Leesa%20Moore%20Named%20to%20Honor%20Roll.png
      label: "Honor Roll"
    - url: /assets/accomplishments/Leesa%20Moore%20Named%20to%20SNHU%20President's%20List%20-%202022.png
      image: /assets/accomplishments/Leesa%20Moore%20Named%20to%20SNHU%20President's%20List%20-%202022.png
      label: "President's List 2022"
    - url: /assets/accomplishments/Leesa%20Moore%20Named%20to%20SNHU%20President's%20List%20-%202023.png
      image: /assets/accomplishments/Leesa%20Moore%20Named%20to%20SNHU%20President's%20List%20-%202023.png
      label: "President's List 2023"
    - url: /assets/accomplishments/SNHU%20Announces%20Honor%20Roll%20for%2023EW4.png
      image: /assets/accomplishments/SNHU%20Announces%20Honor%20Roll%20for%2023EW4.png
      label: "Honor Roll"
    - url: /assets/accomplishments/SNHU%20Announces%20Honor%20Roll%20for%2023EW6.png
      image: /assets/accomplishments/SNHU%20Announces%20Honor%20Roll%20for%2023EW6.png
      label: "Honor Roll"

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude
exclude:
  - README.md
  - Gemfile.lock
  - .jekyll-cache/
  - .github/
  - CHANGELOG.md
  - Gemfile
  - LICENSE.txt
  - funding.yml
  - linkhub-jekyll-theme.gemspec
