# Jekyll Configuration
theme: linkhub-jekyll-theme
baseurl: "/resume.portfolio"

# Site Configuration
name: Leesa Moore's Digital Portfolio
tagline: One hub, all the links you need
description: "Explore my work, connect with me, and discover more."

# Favicon Configuration
favicon:
  path: assets/favicons/favicon-32x32.png
  type: png
logo: assets/favicons/logo.png
# url: https://link.example.com # URL of your website

# Marked up Location
locale: en_GB

# Google Analytics ID
ga4: G-9LJKQM0ZYN

# Used for SEO
twitter:
  username: leeeeesamo
image:
  path: assets/favicons/logo.png
  type: png
  height: 100 
  width: 100
  alt: logo
  
# Verified Badge Configuration
badge:
  enable: true
  icon: ri:verified-badge-fill
  color: '#dfb221'
  
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec, .a_archived]
