# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Leesa Moore's Digital Portfolio      
tagline: Your gateway to my professional world - One hub, all the links you need  
description: Explore my work, connect with me, and discover more.
favicon:
  path: assets/images/lightbulb.png
  type: png 
logo: assets/images/TopNotch.png
url: https://top-notch-solutions.com
locale: en_GB 
ga4: G-9LJKQM0ZYN
twitter:
  username: UserName # Used for SEO
image:
  path: assets/images/example.jpg # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge:
  enable: true # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]